"""agaggavcvdfvfddf

Revision ID: 24952126ebdd
Revises: 
Create Date: 2025-01-29 14:15:40.642406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24952126ebdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plane_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('founded', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planeCompany_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planeCompany_id'], ['plane_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planes_id', sa.Integer(), nullable=False),
    sa.Column('owners_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owners_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['planes_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planes_owners')
    op.drop_table('planes')
    op.drop_table('plane_company')
    op.drop_table('owners')
    # ### end Alembic commands ###
