"""mv

Revision ID: 95f8e1d28f51
Revises: 1b6c4d8687bd
Create Date: 2025-01-29 18:48:29.486833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f8e1d28f51'
down_revision = '1b6c4d8687bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_plane_name', ['name'])

    with op.batch_alter_table('planes_owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plane_name', sa.String(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'planes', ['plane_name'], ['name'])
        batch_op.drop_column('planes_id')
        batch_op.drop_column('owners_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes_owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owners_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('planes_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'planes', ['planes_id'], ['id'])
        batch_op.create_foreign_key(None, 'owners', ['owners_id'], ['id'])
        batch_op.drop_column('plane_name')

    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
