"""create and rename table

Revision ID: ba1524692c95
Revises: 40f44fde8685
Create Date: 2025-01-28 17:09:07.634209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1524692c95'
down_revision = '40f44fde8685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planes_id', sa.Integer(), nullable=False),
    sa.Column('owners_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owners_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['planes_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planesowners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planesowners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('planes_id', sa.INTEGER(), nullable=False),
    sa.Column('owners_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owners_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['planes_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planes_owners')
    # ### end Alembic commands ###
